#ifndef MOD_APPRECIATION_H
#define MOD_APPRECIATION_H

#include "ScriptMgr.h"

enum
{
    GOSSIP_MENU_CHOOSE_SPECIALIZATION   = 100,
    GOSSIP_MENU_SPECIALIZATION_1        = 200,
    GOSSIP_MENU_SPECIALIZATION_2        = 201,
    GOSSIP_MENU_SPECIALIZATION_3        = 202,
    GOSSIP_TEXT_DEFAULT                 = 48,
    GOSSIP_TEXT_CERTIFICATE_MISSING     = 6000000,
    GOSSIP_TEXT_CHOOSE_SPECIALIZATION   = 6000001,
    GOSSIP_TEXT_CONFIRM_SPECIALIZATION  = 6000002,
    GOSSIP_TEXT_CHOOSE_CONTINENT        = 6000003
};

#endif